# Generated by Django 4.2.3 on 2023-07-31 19:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=45)),
                ('phone', models.CharField(max_length=10)),
                ('user_query', models.TextField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_name', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('course_fees', models.IntegerField()),
                ('course_duration', models.CharField(max_length=40)),
                ('course_contents', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback_Ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=45)),
                ('feedback_text', models.TextField()),
                ('rating', models.CharField(max_length=6)),
                ('data', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_contents', models.CharField(max_length=45)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
