# Generated by Django 4.2.3 on 2023-08-01 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_data_feedback_ratings_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feedback_Ratings',
            new_name='Feedback_Rating',
        ),
    ]
