# Generated by Django 4.2.3 on 2023-08-03 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_pic',
            field=models.FileField(default='', max_length=200, upload_to='myapp/employee_pic'),
        ),
    ]
