# Generated by Django 4.2.3 on 2023-08-09 18:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultancy',
            fields=[
                ('c_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('c_password', models.CharField(max_length=40)),
                ('c_name', models.CharField(max_length=45)),
                ('c_phone', models.CharField(max_length=10)),
                ('c_email', models.EmailField(max_length=45)),
                ('c_description', models.TextField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
